# South Africa Agribusiness — Project Bootstrap
# Target root: C:\Projects\Personal\South_Agribusiness

$ErrorActionPreference = "Stop"

$Root = "C:\Projects\Personal\South_Agribusiness"

$Dirs = @(
    "00_CONTROL",
    "01_RESEARCH\01_INDUSTRY",
    "01_RESEARCH\02_MARKETS",
    "01_RESEARCH\03_COMMODITIES",
    "01_RESEARCH\04_AGRICULTURAL_INPUTS",
    "01_RESEARCH\05_FERTILISERS_NPK",
    "01_RESEARCH\06_PESTICIDES_HERBICIDES_FUNGICIDES",
    "01_RESEARCH\07_SEEDS",
    "01_RESEARCH\08_LIVESTOCK_FEED",
    "01_RESEARCH\09_AGROPROCESSING",
    "01_RESEARCH\10_LOGISTICS_STORAGE",
    "01_RESEARCH\11_AGTECH",
    "02_REGULATORY\01_ACTS_REGULATIONS",
    "02_REGULATORY\02_STANDARDS_SANS_ISO",
    "02_REGULATORY\03_REGISTRATIONS_PERMITS",
    "02_REGULATORY\04_LABELS_SDS_TRACEABILITY",
    "02_REGULATORY\05_ENVIRONMENTAL_OHS",
    "03_BUSINESS\01_BUSINESS_MODEL",
    "03_BUSINESS\02_CUSTOMERS",
    "03_BUSINESS\03_COMPETITORS",
    "03_BUSINESS\04_VALUE_CHAINS",
    "03_BUSINESS\05_PRICING_UNIT_ECONOMICS",
    "03_BUSINESS\06_FINANCIAL_MODEL",
    "03_BUSINESS\07_RISK",
    "03_BUSINESS\08_GO_TO_MARKET",
    "04_TECH\01_PRODUCT_REQUIREMENTS",
    "04_TECH\02_ARCHITECTURE",
    "04_TECH\03_DATABASE",
    "04_TECH\04_API",
    "04_TECH\05_FRONTEND",
    "04_TECH\06_TESTS_QA",
    "04_TECH\07_SECURITY",
    "04_TECH\08_DEPLOYMENT",
    "05_OPERATIONS\01_SOPs",
    "05_OPERATIONS\02_QUALITY",
    "05_OPERATIONS\03_PROCUREMENT",
    "05_OPERATIONS\04_INVENTORY",
    "05_OPERATIONS\05_SALES",
    "05_OPERATIONS\06_CUSTOMER_SUPPORT",
    "06_EVIDENCE\01_SOURCE_REGISTER",
    "06_EVIDENCE\02_CLAIMS_REGISTER",
    "06_EVIDENCE\03_COMPLIANCE_MATRIX",
    "06_EVIDENCE\04_DECISIONS",
    "06_EVIDENCE\05_AUDIT_TRAIL",
    "07_IMPLEMENTATION_PACKETS",
    "08_FINANCE",
    "09_LEGAL",
    "10_MARKETING",
    "11_ARCHIVE"
)

New-Item -ItemType Directory -Force -Path $Root | Out-Null
foreach ($Dir in $Dirs) {
    New-Item -ItemType Directory -Force -Path (Join-Path $Root $Dir) | Out-Null
}

Write-Host "Project bootstrap completed: $Root" -ForegroundColor Green
